version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - maum-lab
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    init: true
    tty: true

  backend:
    depends_on:
      - postgres
    build: .
    restart: always
    ports:
      - 4000:4000
    networks:
      - maum-lab
    environment:
      TZ: Asia/Seoul
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    tty: true

networks:
  maum-lab:
    driver: bridge
